/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.asistant;
import UI.eventMasterPro;
import java.awt.BorderLayout;


/**
 *
 * @author kevin
 */
public class assistantMainUI extends javax.swing.JFrame {

    /**
     * Creates new form assistantMainUI
     */
    public assistantMainUI() {
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        windowAssistant = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReturn = new javax.swing.JMenu();
        jMenuItemReturn = new javax.swing.JMenuItem();
        jMenuEvents = new javax.swing.JMenu();
        jMenuItemViewEvents = new javax.swing.JMenuItem();
        jMenuTickets = new javax.swing.JMenu();
        jMenuItemBuyTicket = new javax.swing.JMenuItem();
        jMenuvalidator = new javax.swing.JMenu();
        jMenuItemValidateTicket = new javax.swing.JMenuItem();
        jMenuHistory = new javax.swing.JMenu();
        jMenuItemHistory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout windowAssistantLayout = new javax.swing.GroupLayout(windowAssistant);
        windowAssistant.setLayout(windowAssistantLayout);
        windowAssistantLayout.setHorizontalGroup(
            windowAssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        windowAssistantLayout.setVerticalGroup(
            windowAssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jMenuReturn.setText("Return");

        jMenuItemReturn.setText("Return");
        jMenuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReturnActionPerformed(evt);
            }
        });
        jMenuReturn.add(jMenuItemReturn);

        jMenuBar1.add(jMenuReturn);

        jMenuEvents.setText("Events");

        jMenuItemViewEvents.setText("View Events");
        jMenuItemViewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewEventsActionPerformed(evt);
            }
        });
        jMenuEvents.add(jMenuItemViewEvents);

        jMenuBar1.add(jMenuEvents);

        jMenuTickets.setText("Tickets");

        jMenuItemBuyTicket.setText("Buy Ticket");
        jMenuItemBuyTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuyTicketActionPerformed(evt);
            }
        });
        jMenuTickets.add(jMenuItemBuyTicket);

        jMenuBar1.add(jMenuTickets);

        jMenuvalidator.setText("Validator");

        jMenuItemValidateTicket.setText("Validate Ticket");
        jMenuItemValidateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidateTicketActionPerformed(evt);
            }
        });
        jMenuvalidator.add(jMenuItemValidateTicket);

        jMenuBar1.add(jMenuvalidator);

        jMenuHistory.setText("History");

        jMenuItemHistory.setText("History");
        jMenuItemHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoryActionPerformed(evt);
            }
        });
        jMenuHistory.add(jMenuItemHistory);

        jMenuBar1.add(jMenuHistory);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemViewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewEventsActionPerformed
        ViewEvents VEUI = new ViewEvents();
        //VEUI = View Events UI
        VEUI.setSize(1188, 685);
        VEUI.setLocation(0, 0);

        windowAssistant.removeAll();
        windowAssistant.add(VEUI, BorderLayout.CENTER);
        windowAssistant.revalidate();
        windowAssistant.repaint();
    }//GEN-LAST:event_jMenuItemViewEventsActionPerformed

    private void jMenuItemBuyTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuyTicketActionPerformed
        BuyTicket BTUI = new BuyTicket();
        BTUI.setSize(1188, 685);
        BTUI.setLocation(0, 0);
        //BTUI = Buy Ticket UI
        windowAssistant.removeAll();
        windowAssistant.add(BTUI, BorderLayout.CENTER);
        windowAssistant.revalidate();
        windowAssistant.repaint();
    }//GEN-LAST:event_jMenuItemBuyTicketActionPerformed

    private void jMenuItemValidateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidateTicketActionPerformed
        ValidateTicket VTUI = new ValidateTicket();
        VTUI.setSize(1188, 685);
        VTUI.setLocation(0, 0);
        //VtUI = Validate Ticket UI
        windowAssistant.removeAll();
        windowAssistant.add(VTUI, BorderLayout.CENTER);
        windowAssistant.revalidate();
        windowAssistant.repaint();
    }//GEN-LAST:event_jMenuItemValidateTicketActionPerformed

    private void jMenuItemHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoryActionPerformed
        History HUI = new History();
        HUI.setSize(1188, 685);
        HUI.setLocation(0, 0);
        //HUI = History UI
        windowAssistant.removeAll();
        windowAssistant.add(HUI, BorderLayout.CENTER);
        windowAssistant.revalidate();
        windowAssistant.repaint();
    }//GEN-LAST:event_jMenuItemHistoryActionPerformed

    private void jMenuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReturnActionPerformed
        UI.eventMasterPro mainUI = new UI.eventMasterPro();
        mainUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assistantMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assistantMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assistantMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assistantMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assistantMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEvents;
    private javax.swing.JMenu jMenuHistory;
    private javax.swing.JMenuItem jMenuItemBuyTicket;
    private javax.swing.JMenuItem jMenuItemHistory;
    private javax.swing.JMenuItem jMenuItemReturn;
    private javax.swing.JMenuItem jMenuItemValidateTicket;
    private javax.swing.JMenuItem jMenuItemViewEvents;
    private javax.swing.JMenu jMenuReturn;
    private javax.swing.JMenu jMenuTickets;
    private javax.swing.JMenu jMenuvalidator;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPanel windowAssistant;
    // End of variables declaration//GEN-END:variables
}
