/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.administrator;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author kevin
 */
public class administratorMainUi extends javax.swing.JFrame {

    /**
     * Creates new form administratorMainUi
     */
    public administratorMainUi() {
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage () {
        String img = "/logo.png";
        URL url = getClass().getResource(img);
        if (url == null) {
            System.err.println("No se encontró el recurso: " + img);
            return null;
        }
        System.out.println("URL del recurso: " + url);
        return Toolkit.getDefaultToolkit().getImage(url); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        windowAdministrator = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReturn = new javax.swing.JMenu();
        jMenuItemReturn = new javax.swing.JMenuItem();
        jMenuEvents = new javax.swing.JMenu();
        jMenuItemCreateEvent = new javax.swing.JMenuItem();
        jMenuItemListEvents = new javax.swing.JMenuItem();
        jMenuItemModifyEvent = new javax.swing.JMenuItem();
        jMenuItemDeleteEvent = new javax.swing.JMenuItem();
        jMenuLocations = new javax.swing.JMenu();
        jMenuItemCreateLocation = new javax.swing.JMenuItem();
        jMenuItemListLocations = new javax.swing.JMenuItem();
        jMenuArtists = new javax.swing.JMenu();
        jMenuItemCreateArtists = new javax.swing.JMenuItem();
        jMenuItemListArtists = new javax.swing.JMenuItem();
        jMenuItemAddRecord = new javax.swing.JMenuItem();
        jMenuItemListArtistRecords = new javax.swing.JMenuItem();
        jMenuTicketsAndSales = new javax.swing.JMenu();
        jMenuItemCreateTicketForEvent = new javax.swing.JMenuItem();
        jMenuItemListTickets = new javax.swing.JMenuItem();
        jMenuItemModifyTickets = new javax.swing.JMenuItem();
        jMenuStadistics = new javax.swing.JMenu();
        jMenuItemStadistics = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout windowAdministratorLayout = new javax.swing.GroupLayout(windowAdministrator);
        windowAdministrator.setLayout(windowAdministratorLayout);
        windowAdministratorLayout.setHorizontalGroup(
            windowAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        windowAdministratorLayout.setVerticalGroup(
            windowAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 255));

        jMenuReturn.setText("Return");

        jMenuItemReturn.setText("Return");
        jMenuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReturnActionPerformed(evt);
            }
        });
        jMenuReturn.add(jMenuItemReturn);

        jMenuBar1.add(jMenuReturn);

        jMenuEvents.setText("Events");

        jMenuItemCreateEvent.setText("Create Event");
        jMenuItemCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateEventActionPerformed(evt);
            }
        });
        jMenuEvents.add(jMenuItemCreateEvent);

        jMenuItemListEvents.setText("List Events");
        jMenuItemListEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListEventsActionPerformed(evt);
            }
        });
        jMenuEvents.add(jMenuItemListEvents);

        jMenuItemModifyEvent.setText("Modify Events");
        jMenuItemModifyEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifyEventActionPerformed(evt);
            }
        });
        jMenuEvents.add(jMenuItemModifyEvent);

        jMenuItemDeleteEvent.setText("Delete event");
        jMenuItemDeleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteEventActionPerformed(evt);
            }
        });
        jMenuEvents.add(jMenuItemDeleteEvent);

        jMenuBar1.add(jMenuEvents);

        jMenuLocations.setText("Locations");

        jMenuItemCreateLocation.setText("Create Location");
        jMenuItemCreateLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateLocationActionPerformed(evt);
            }
        });
        jMenuLocations.add(jMenuItemCreateLocation);

        jMenuItemListLocations.setText("List Locations");
        jMenuItemListLocations.setToolTipText("");
        jMenuItemListLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListLocationsActionPerformed(evt);
            }
        });
        jMenuLocations.add(jMenuItemListLocations);

        jMenuBar1.add(jMenuLocations);

        jMenuArtists.setText("Artists and Records");

        jMenuItemCreateArtists.setText("Create Artist");
        jMenuItemCreateArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateArtistsActionPerformed(evt);
            }
        });
        jMenuArtists.add(jMenuItemCreateArtists);

        jMenuItemListArtists.setText("List Artists");
        jMenuItemListArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListArtistsActionPerformed(evt);
            }
        });
        jMenuArtists.add(jMenuItemListArtists);

        jMenuItemAddRecord.setText("Add Record");
        jMenuItemAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddRecordActionPerformed(evt);
            }
        });
        jMenuArtists.add(jMenuItemAddRecord);

        jMenuItemListArtistRecords.setText("List Artist Records");
        jMenuItemListArtistRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListArtistRecordsActionPerformed(evt);
            }
        });
        jMenuArtists.add(jMenuItemListArtistRecords);

        jMenuBar1.add(jMenuArtists);

        jMenuTicketsAndSales.setText("Tickets and Sales");

        jMenuItemCreateTicketForEvent.setText("Create Tickets for Event");
        jMenuItemCreateTicketForEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateTicketForEventActionPerformed(evt);
            }
        });
        jMenuTicketsAndSales.add(jMenuItemCreateTicketForEvent);

        jMenuItemListTickets.setText("List Tickets");
        jMenuItemListTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListTicketsActionPerformed(evt);
            }
        });
        jMenuTicketsAndSales.add(jMenuItemListTickets);

        jMenuItemModifyTickets.setText("Modify Tickets");
        jMenuItemModifyTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifyTicketsActionPerformed(evt);
            }
        });
        jMenuTicketsAndSales.add(jMenuItemModifyTickets);

        jMenuBar1.add(jMenuTicketsAndSales);

        jMenuStadistics.setText("Stadistics");

        jMenuItemStadistics.setText("Stadistics");
        jMenuItemStadistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStadisticsActionPerformed(evt);
            }
        });
        jMenuStadistics.add(jMenuItemStadistics);

        jMenuBar1.add(jMenuStadistics);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateTicketForEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateTicketForEventActionPerformed
        UI.administrator.ticketsAndSales.CreateTicketsForEvent CTFEUI = new UI.administrator.ticketsAndSales.CreateTicketsForEvent();
        CTFEUI.setSize(1188, 685);
        CTFEUI.setLocation(0, 0);
        //CTFEUI = Create Tickets For Event UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(CTFEUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemCreateTicketForEventActionPerformed

    private void jMenuItemListTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListTicketsActionPerformed
        UI.administrator.ticketsAndSales.ListTickets LTUI = new UI.administrator.ticketsAndSales.ListTickets();
        LTUI.setSize(1188, 685);
        LTUI.setLocation(0, 0);
        //LTUI = List Ticket UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(LTUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemListTicketsActionPerformed

    private void jMenuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReturnActionPerformed
        UI.eventMasterPro mainUI = new UI.eventMasterPro();
        mainUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemReturnActionPerformed

    private void jMenuItemCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateEventActionPerformed
        UI.administrator.events.CreateEvent CEUI = new UI.administrator.events.CreateEvent();
        CEUI.setSize(1188, 685);
        CEUI.setLocation(0, 0);
        //CEUI = Create Event UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(CEUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemCreateEventActionPerformed

    private void jMenuItemListEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListEventsActionPerformed
        UI.administrator.events.ListEvents LEUI = new UI.administrator.events.ListEvents();
        LEUI.setSize(1188, 685);
        LEUI.setLocation(0, 0);
        //LEUI = List Events UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(LEUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemListEventsActionPerformed

    private void jMenuItemModifyEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifyEventActionPerformed
        UI.administrator.events.ModifyEvent MEUI = new UI.administrator.events.ModifyEvent();
        MEUI.setSize(1188, 685);
        MEUI.setLocation(0, 0);
        //MEUI = Modify Event UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(MEUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemModifyEventActionPerformed

    private void jMenuItemDeleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteEventActionPerformed
        UI.administrator.events.DeleteEvent DEUI = new UI.administrator.events.DeleteEvent();
        DEUI.setSize(1188, 685);
        DEUI.setLocation(0, 0);
        //DEUI = Delete Event UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(DEUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemDeleteEventActionPerformed

    private void jMenuItemCreateLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateLocationActionPerformed
        UI.administrator.locations.CreateLocation CLUI = new UI.administrator.locations.CreateLocation();
        CLUI.setSize(1188, 685);
        CLUI.setLocation(0, 0);
        //CLUI = Create Location UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(CLUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemCreateLocationActionPerformed

    private void jMenuItemListLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListLocationsActionPerformed
        UI.administrator.locations.ListLocations LLUI = new UI.administrator.locations.ListLocations();
        LLUI.setSize(1188, 685);
        LLUI.setLocation(0, 0);
        //LLUI = List Locations UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(LLUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemListLocationsActionPerformed

    private void jMenuItemCreateArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateArtistsActionPerformed
        UI.administrator.artists.CreateArtist CAUI = new UI.administrator.artists.CreateArtist();
        CAUI.setSize(1188, 685);
        CAUI.setLocation(0, 0);
        //CAUI = Create Artist UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(CAUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemCreateArtistsActionPerformed

    private void jMenuItemListArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListArtistsActionPerformed
        UI.administrator.artists.ListArtists LAUI = new UI.administrator.artists.ListArtists();
        LAUI.setSize(1188, 685);
        LAUI.setLocation(0, 0);
        //LAUI = List Artists UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(LAUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemListArtistsActionPerformed

    private void jMenuItemModifyTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifyTicketsActionPerformed
        UI.administrator.ticketsAndSales.ModifyTicket MTUI = new UI.administrator.ticketsAndSales.ModifyTicket();
        MTUI.setSize(1188, 685);
        MTUI.setLocation(0, 0);
        //MTUI = Modify Ticket UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(MTUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemModifyTicketsActionPerformed

    private void jMenuItemStadisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStadisticsActionPerformed
        UI.administrator.Stadistics.Stadistics SUI = new UI.administrator.Stadistics.Stadistics();
        SUI.setSize(1188, 685);
        SUI.setLocation(0, 0);
        //SUI = Stadistics UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(SUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();    }//GEN-LAST:event_jMenuItemStadisticsActionPerformed

    private void jMenuItemAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddRecordActionPerformed
        UI.administrator.artists.AddRecord ARUI = new UI.administrator.artists.AddRecord();
        ARUI.setSize(1188, 685);
        ARUI.setLocation(0, 0);
        //ARUI = Add Record UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(ARUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemAddRecordActionPerformed

    private void jMenuItemListArtistRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListArtistRecordsActionPerformed
        UI.administrator.artists.ListArtistRecords LARUI = new UI.administrator.artists.ListArtistRecords();
        LARUI.setSize(1188, 685);
        LARUI.setLocation(0, 0);
        //LARUI = List Artist Record UI
        
        windowAdministrator.removeAll();
        windowAdministrator.add(LARUI, BorderLayout.CENTER);
        windowAdministrator.revalidate();
        windowAdministrator.repaint();
    }//GEN-LAST:event_jMenuItemListArtistRecordsActionPerformed

    /*
    public static void setIcon(JFrame frame){
        Image ico = Toolkit.getDefaultToolkit().getImage(ImageUtil.class.getResource("logo.png"));
        frame.setIconImage(ico);
    }
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administratorMainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administratorMainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administratorMainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administratorMainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administratorMainUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuArtists;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEvents;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAddRecord;
    private javax.swing.JMenuItem jMenuItemCreateArtists;
    private javax.swing.JMenuItem jMenuItemCreateEvent;
    private javax.swing.JMenuItem jMenuItemCreateLocation;
    private javax.swing.JMenuItem jMenuItemCreateTicketForEvent;
    private javax.swing.JMenuItem jMenuItemDeleteEvent;
    private javax.swing.JMenuItem jMenuItemListArtistRecords;
    private javax.swing.JMenuItem jMenuItemListArtists;
    private javax.swing.JMenuItem jMenuItemListEvents;
    private javax.swing.JMenuItem jMenuItemListLocations;
    private javax.swing.JMenuItem jMenuItemListTickets;
    private javax.swing.JMenuItem jMenuItemModifyEvent;
    private javax.swing.JMenuItem jMenuItemModifyTickets;
    private javax.swing.JMenuItem jMenuItemReturn;
    private javax.swing.JMenuItem jMenuItemStadistics;
    private javax.swing.JMenu jMenuLocations;
    private javax.swing.JMenu jMenuReturn;
    private javax.swing.JMenu jMenuStadistics;
    private javax.swing.JMenu jMenuTicketsAndSales;
    private javax.swing.JPanel windowAdministrator;
    // End of variables declaration//GEN-END:variables
}
